(import "nat-church.lisp" zero add1 sub1 zero?)
(import "nat-church.lisp" one two three four five)
(import "bool.lisp" if)

(define (ackermann m n)
  (if (zero? m)
    (add1 n)
    (if (zero? n)
      (ackermann (sub1 m) one)
      (ackermann (sub1 m) (ackermann m (sub1 n))))))

(assert-bisimilar (ackermann zero zero) one)
(assert-bisimilar (ackermann one zero) two)
(assert-bisimilar (ackermann zero one) two)
(assert-bisimilar (ackermann two zero) three)
(assert-bisimilar (ackermann one one) three)
(assert-bisimilar (ackermann zero two) three)
(assert-bisimilar (ackermann three zero) five)
(assert-bisimilar (ackermann two one) five)
(assert-bisimilar (ackermann one two) four)
(assert-bisimilar (ackermann zero three) four)

(assert-bisimilar
  ackermann
  (lambda (m n)
    (if (zero? m)
      (add1 n)
      (if (zero? n)
        (ackermann (sub1 m) one)
        (ackermann (sub1 m) (ackermann m (sub1 n)))))))

(assert-bisimilar
  ackermann
  (lambda (m n)
    (if (zero? m)
      (add1 n)
      (if (zero? n)
        (ackermann (sub1 m) one)
        ((lambda (m n)
           (if (zero? m)
             (add1 n)
             (if (zero? n)
               (ackermann (sub1 m) one)
               (ackermann (sub1 m) (ackermann m (sub1 n))))))
         (sub1 m)
         (ackermann m (sub1 n)))))))

(define (ackermann/1 m n)
  (if (zero? m)
    (add1 n)
    (if (zero? n)
      (ackermann/1 (sub1 m) one)
      ((lambda (m n)
         (if (zero? m)
           (add1 n)
           (if (zero? n)
             (ackermann/1 (sub1 m) one)
             (ackermann/1 (sub1 m) (ackermann/1 m (sub1 n))))))
       (sub1 m)
       (ackermann/1 m (sub1 n))))))

(assert-bisimilar (ackermann/1 zero zero) one)
(assert-bisimilar (ackermann/1 one zero) two)
(assert-bisimilar (ackermann/1 zero one) two)
(assert-bisimilar (ackermann/1 two zero) three)
(assert-bisimilar (ackermann/1 one one) three)
(assert-bisimilar (ackermann/1 zero two) three)
(assert-bisimilar (ackermann/1 three zero) five)
(assert-bisimilar (ackermann/1 two one) five)
(assert-bisimilar (ackermann/1 one two) four)
(assert-bisimilar (ackermann/1 zero three) four)

(assert-bisimilar ackermann ackermann/1)

(assert-bisimilar
  (lambda (m n)
    (if (zero? m)
      (add1 n)
      (if (zero? n)
        (ackermann (sub1 m) one)
        (ackermann (sub1 m) (ackermann m (sub1 n))))))
  (lambda (m n)
    (if (zero? m)
      (add1 n)
      (if (zero? n)
        (ackermann (sub1 m) one)
        ((lambda (m n)
           (if (zero? m)
             (add1 n)
             (if (zero? n)
               (ackermann (sub1 m) one)
               (ackermann (sub1 m) (ackermann m (sub1 n))))))
         (sub1 m)
         (ackermann m (sub1 n)))))))

(assert-bisimilar
  ackermann
  (lambda (m n)
    (if (zero? m)
      (add1 n)
      (if (zero? n)
        ((lambda (m n)
           (if (zero? m)
             (add1 n)
             (if (zero? n)
               (ackermann (sub1 m) one)
               (ackermann (sub1 m) (ackermann m (sub1 n))))))
         (sub1 m) one)
        ((lambda (m n)
           (if (zero? m)
             (add1 n)
             (if (zero? n)
               (ackermann (sub1 m) one)
               (ackermann (sub1 m) (ackermann m (sub1 n))))))
         (sub1 m)
         ((lambda (m n)
            (if (zero? m)
              (add1 n)
              (if (zero? n)
                (ackermann (sub1 m) one)
                (ackermann (sub1 m) (ackermann m (sub1 n))))))
          m (sub1 n)))))))

(assert-bisimilar
  ackermann
  (lambda (m n)
    (if (zero? m)
      (add1 n)
      (if (zero? n)
        (if (zero? (sub1 m))
          (add1 one)
          (if (zero? one)
            (ackermann (sub1 (sub1 m)) one)
            (ackermann (sub1 (sub1 m)) (ackermann (sub1 m) (sub1 one)))))
        ((lambda (m n)
           (if (zero? m)
             (add1 n)
             (if (zero? n)
               (ackermann (sub1 m) one)
               (ackermann (sub1 m) (ackermann m (sub1 n))))))
         (sub1 m)
         ((lambda (m n)
            (if (zero? m)
              (add1 n)
              (if (zero? n)
                (ackermann (sub1 m) one)
                (ackermann (sub1 m) (ackermann m (sub1 n))))))
          m (sub1 n)))))))
