(import "nat-church.lisp" zero add1 sub1 zero?)
(import "nat-church.lisp" one two three four five)
(import "bool.lisp" if)
(import "fixpoint.lisp" Y)
(import "ackermann.lisp" ackermann)

(define ackermann-wrap
  (lambda (ackermann)
    (lambda (m n)
      (if (zero? m)
        (add1 n)
        (if (zero? n)
          (ackermann (sub1 m) one)
          (ackermann (sub1 m) (ackermann m (sub1 n))))))))

(assert-bisimilar ((Y ackermann-wrap) zero zero) one)
;; (assert-bisimilar ((Y ackermann-wrap) one zero) two)
;; (assert-bisimilar ((Y ackermann-wrap) zero one) two)
;; (assert-bisimilar ((Y ackermann-wrap) two zero) three)
;; (assert-bisimilar ((Y ackermann-wrap) one one) three)
;; (assert-bisimilar ((Y ackermann-wrap) zero two) three)
;; (assert-bisimilar ((Y ackermann-wrap) three zero) five)
;; (assert-bisimilar ((Y ackermann-wrap) two one) five)
;; (assert-bisimilar ((Y ackermann-wrap) one two) four)
;; (assert-bisimilar ((Y ackermann-wrap) zero three) four)

(assert-bisimilar ackermann (ackermann-wrap ackermann))
(assert-bisimilar ackermann (ackermann-wrap (ackermann-wrap ackermann)))

(define (ackermann-1 m n)
  ((ackermann-wrap ackermann-1)
   m n))

(assert-bisimilar (ackermann-1 zero zero) one)
(assert-bisimilar (ackermann-1 one zero) two)
(assert-bisimilar (ackermann-1 zero one) two)
(assert-bisimilar (ackermann-1 two zero) three)
(assert-bisimilar (ackermann-1 one one) three)
(assert-bisimilar (ackermann-1 zero two) three)
(assert-bisimilar (ackermann-1 three zero) five)
(assert-bisimilar (ackermann-1 two one) five)
(assert-bisimilar (ackermann-1 one two) four)
(assert-bisimilar (ackermann-1 zero three) four)

(define (ackermann-2 m n)
  ((ackermann-wrap
    (ackermann-wrap ackermann-2))
   m n))

(assert-bisimilar (ackermann-2 zero zero) one)
(assert-bisimilar (ackermann-2 one zero) two)
(assert-bisimilar (ackermann-2 zero one) two)
(assert-bisimilar (ackermann-2 two zero) three)
(assert-bisimilar (ackermann-2 one one) three)
(assert-bisimilar (ackermann-2 zero two) three)
(assert-bisimilar (ackermann-2 three zero) five)
(assert-bisimilar (ackermann-2 two one) five)
(assert-bisimilar (ackermann-2 one two) four)
(assert-bisimilar (ackermann-2 zero three) four)

(define (ackermann-3 m n)
  ((ackermann-wrap
    (ackermann-wrap
     (ackermann-wrap ackermann-3)))
   m n))

(assert-bisimilar (ackermann-3 zero zero) one)
(assert-bisimilar (ackermann-3 one zero) two)
(assert-bisimilar (ackermann-3 zero one) two)
(assert-bisimilar (ackermann-3 two zero) three)
(assert-bisimilar (ackermann-3 one one) three)
(assert-bisimilar (ackermann-3 zero two) three)
(assert-bisimilar (ackermann-3 three zero) five)
(assert-bisimilar (ackermann-3 two one) five)
(assert-bisimilar (ackermann-3 one two) four)
(assert-bisimilar (ackermann-3 zero three) four)

(assert-bisimilar ackermann-1 ackermann-2)
(assert-bisimilar ackermann-1 ackermann-3)
(assert-bisimilar ackermann-2 ackermann-3)
